name = "FFTLog"
uuid = "a00cc2bc-8b4a-4b7f-b12a-0794eb62aad9"
authors = ["marcobonici <bonici.marco@gmail.com>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
FFTW = "1"
SpecialFunctions = "2"
